version: '3'

services:
  db:
    image: postgres:9.6
    container_name: etfocs-postgres
    volumes:
      - "./db-data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    env_file:
      - .env_postgres
  be:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env_postgres
    depends_on:
      - db
  fe:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '4200:4200'
