# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsetup',
            name='title',
            field=models.CharField(default='Basics Test', max_length=255),
            preserve_default=False,
        ),
    ]
