# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_testsetup_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='jmbg',
            field=models.CharField(max_length=13),
        ),
    ]
