# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171119_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtest',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Duration (in hours)'),
        ),
    ]
