# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-16 23:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20171216_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='scheduled_test_result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.ScheduledTestResult'),
        ),
    ]
