# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-16 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20171216_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='predefined_answers',
            field=models.ManyToManyField(null=True, related_name='answers', to='api.PredefinedAnswer'),
        ),
    ]
